# Generated by Django 4.1.7 on 2023-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_appuser_managers_remove_appuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(default='3116', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
