# Generated by Django 4.1.7 on 2023-02-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_appuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
    ]
