# Generated by Django 4.1.7 on 2023-03-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='achievements',
            field=models.ManyToManyField(to='homepage.achievement'),
        ),
    ]
