# Generated by Django 4.1.7 on 2023-03-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='achievements',
            field=models.ManyToManyField(related_name='user_achievements', to='homepage.achievement'),
        ),
    ]
