version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./db.env
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    image: django-server
    ports:
      - 8000:8000
    restart: always
    container_name: django_server
    env_file:
      - ./aws.env
    depends_on:
      - db
    volumes:
      - django_backend:/user/backend
volumes:
  django_backend:
  postgres_data:
