# Generated by Django 4.1.7 on 2023-03-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='text',
        ),
    ]
