# Generated by Django 4.1.7 on 2023-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitymembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymembers',
            name='moderator',
        ),
        migrations.AddField(
            model_name='communitymembers',
            name='moderator_level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
