# Generated by Django 4.1.7 on 2023-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_communitymembers_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='community',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
