# Generated by Django 4.1.7 on 2023-04-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_community_photo'),
        ('community', '0004_community_community_photo_community_member_count'),
    ]

    operations = [
    ]
