# Generated by Django 4.1.7 on 2023-03-08 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmessage_sender'),
        ('community', '0001_initial'),
        ('exercises', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='chat_groups',
            field=models.ManyToManyField(to='chat.chatgroup'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='communities',
            field=models.ManyToManyField(to='community.community'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='exercise_regimes',
            field=models.ManyToManyField(through='exercises.ExerciseRegimeStatistics', to='exercises.exerciseregime'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='exercises',
            field=models.ManyToManyField(through='exercises.ExerciseStatistics', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='privacy_level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
