# Generated by Django 4.1.7 on 2023-03-17 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appuser_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='blocked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
