# Generated by Django 4.1.7 on 2023-04-12 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
