# Generated by Django 4.1.7 on 2023-04-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='calories_burnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
