# Generated by Django 4.1.7 on 2023-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_appuser_calories_burnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='perfect_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
