# Generated by Django 4.1.7 on 2023-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_appuser_perfect_reps_appuser_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
