# Generated by Django 4.1.7 on 2023-04-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appuser_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='longest_streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
