# Generated by Django 4.1.7 on 2023-04-19 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_communitymembers_moderator_and_more'),
        ('users', '0012_appuser_active_appuser_longest_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='appuser',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='blocked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='communities',
            field=models.ManyToManyField(blank=True, through='community.CommunityMembers', to='community.community'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
