# Generated by Django 4.1.7 on 2023-04-19 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_appuser_friends_appuser_friend_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='friend_requests',
        ),
        migrations.AddField(
            model_name='appuser',
            name='sent_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
