# Generated by Django 4.1.7 on 2023-03-10 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0003_exerciseregime_like_count_exercisedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.AddField(
            model_name='exercise',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='likers',
            field=models.ManyToManyField(related_name='%(class)s_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='poster',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
