# Generated by Django 4.1.7 on 2023-03-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_media_exercise_shared_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseregime',
            name='description',
        ),
    ]
