# Generated by Django 4.1.7 on 2023-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_communitypost_tags_alter_userpost_tags'),
        ('exercises', '0009_alter_exercise_text_alter_exerciseregime_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='total_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercisestatistics',
            name='total_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feed.tags'),
        ),
        migrations.AlterField(
            model_name='exerciseregime',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feed.tags'),
        ),
    ]
