# Generated by Django 4.1.7 on 2023-04-11 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0010_exercise_total_reps_exercisestatistics_total_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciseregime',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
