# Generated by Django 4.1.7 on 2023-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_alter_exercise_likers_alter_exerciseregime_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
