# Generated by Django 4.1.7 on 2023-04-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_exercise_title_exerciseregime_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
    ]
