# Generated by Django 4.1.7 on 2023-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_exercisesessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesessions',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
