# Generated by Django 4.1.7 on 2023-04-15 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0016_exercisesessions_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseSessions',
            new_name='ExerciseSession',
        ),
    ]
