name: Django CI Tests for dev branch

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  django-tests-dev:
    name: Django CI Tests for dev branch
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: P@ssword1234
          POSTGRES_DB: flex
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Pipenv
        run: |
          pip3 install pipenv
      - name: Install Dependencies
        run: |
          cd ./backend
          pwd
          pipenv install
      - name: Run Tests
        run: |
          cd ./backend
          pipenv run python manage.py check
          pipenv run python manage.py test
      - name: Merge dev branch into prod
        uses: peter-evans/create-pull-request@v5
        with:
          branch: prod
          token: ${{ secrets.TOKEN }}
