name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: harmon758/postgresql-action@v1
      with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
    - name: Install Pipenv
      run: |
        pip3 install pipenv
    - name: Install Dependencies
      run: |
        cd ./backend
        pwd
        pipenv install 
    - name: Run Tests
      run: |
        cd ./backend
        pipenv run python manage.py check
        pipenv run python manage.py test
