# Generated by Django 4.1.7 on 2023-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_comment_tags_remove_communitypostcomment_commenter_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='feed_commen_content_e2899a_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='parent_type',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userpost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_type', 'parent_id'], name='feed_commen_parent__e0b813_idx'),
        ),
    ]
