# Generated by Django 4.1.7 on 2023-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_comment_poster_alter_communitypost_poster_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communitypost',
            name='feed_commun_content_4cd94c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpost',
            name='feed_userpo_content_118dbd_idx',
        ),
        migrations.RenameField(
            model_name='communitypost',
            old_name='object_id',
            new_name='shared_id',
        ),
        migrations.RenameField(
            model_name='communitypost',
            old_name='content_type',
            new_name='shared_type',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='object_id',
            new_name='shared_id',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='content_type',
            new_name='shared_type',
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['shared_type', 'shared_id'], name='feed_commun_shared__e4bfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='userpost',
            index=models.Index(fields=['shared_type', 'shared_id'], name='feed_userpo_shared__a57062_idx'),
        ),
    ]
