# Generated by Django 4.1.7 on 2023-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_remove_communitypost_feed_commun_content_4cd94c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
