# Generated by Django 4.1.7 on 2023-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_comment_like_count_communitypost_like_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='communitypost',
            old_name='likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='likes',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
