# Generated by Django 4.1.7 on 2023-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_rename_like_count_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
