# Generated by Django 4.1.7 on 2023-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_comment_text_alter_communitypost_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feed.tags'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feed.tags'),
        ),
    ]
