# Generated by Django 4.1.7 on 2023-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_comment_likers_alter_communitypost_likers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userpost',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
